### ISSUE TITLE
Invalid \@ptsize assumptions

### ISSUE THREAD

**Issue by jspitz** [rf-latex/setspace#5]
setspace assumes (in `\onehalfspacing` and `\doublespacing`)

1. That all classes define `\@ptsize`. This is not true, for instance, with beamer, which defines its own macro `\beamer@size`
2. That all classes define `\@ptsize` in the way the standard classes do, setting only the last digit (e.g., `0` for `10pt`). This is not true for many classes (such as the KOMA classes or extsize) which set the whole size (e.g., `10` for `10pt`), as they provide sizes < 10pt or > 20pt.

I think that setspace should 

- Ad 1: either `\providecommand*\@ptsize{0}` and issue a warning if the command has not been defined, or issue an error if `\@ptsize` is undefined (I'd opt for the former, as the setspace macros actually are usable in that case, although the spacing might be not ideal). 
- Ad 2: be able to detect other `\@ptsize` definitions than `0`, `1` and `2`. Of course, ideally it should provide `\setstretch` values for other sizes than 10, 11, and 12. The package should probably also warn if the detected `\@ptsize` value is not supported and it falls back to the default.

**Comment by jspitz** [comment]
Or maybe rely on `\f@size` rather than on `\@ptsize`?

**Comment by jspitz** [comment]
This seems to work well for me:
```tex
\newcommand{\onehalfspacing}{%
  \setstretch{1.25}%  default
  \ifx\f@size\@xpt% 10pt
    \setstretch {1.25}%
  \else
    \ifx\f@size\@xipt% 11pt
       \setstretch {1.213}%
    \else
       \ifx\f@size\@xiipt% 12pt
          \setstretch {1.241}%
       \else       
          \PackageWarning{setspace}{Font size \f@size pt not supported by onehalfspacing\MessageBreak
                                    Accounting for default (10pt)}%
       \fi
     \fi
  \fi
}

\newcommand{\doublespacing}{%
  \setstretch {1.667}%  default
    \ifx\f@size\@xpt% 10pt
    \setstretch {1.667}%
  \else
    \ifx\f@size\@xipt% 11pt
       \setstretch {1.618}%
    \else
       \ifx\f@size\@xiipt% 12pt
          \setstretch {1.655}%
       \else       
          \PackageWarning{setspace}{Font size \f@size pt not supported by doublespacing\MessageBreak
                                    Accounting for default (10pt)}%
       \fi
     \fi
  \fi
}

```

**Comment by davidcarlisle** [comment]
We'll  look,  I suspect if we do anything we'd want to keep the test for \@ptsize=0,1,2 for compatibility then fall back to testing \f@size (which would need `\ifdim`  tests not `\ifx` I think, to catch all cases).

That said it really isn't clear why 1.667 isn't just as good as 1.655 even at 12pt, so arguably all classes are supported and we could simply drop the warning, or make it a log-only Info message.

A test against \f@size would probably need to first locally use `\normalsize` as I don't think \doublespacing should set a different factor (for all sizes) just because it happens in the scope of `\large`

**Comment by jspitz** [comment]
> We'll look, I suspect if we do anything we'd want to keep the test for @ptsize=0,1,2 for compatibility then fall back to testing \f@size (which would need `\ifdim` tests not `\ifx` I think, to catch all cases).

Why? I think all classes set `\f@size`, don't they?

> That said it really isn't clear why 1.667 isn't just as good as 1.655 even at 12pt, so arguably all classes are supported and we could simply drop the warning, or make it a log-only Info message.

It will probably make a bigger difference with very large (e.g., 22pt) or very small (e.g., 8pt) font sizes, so a warning might be appropriate. 

> A test against \f@size would probably need to first locally use `\normalsize` as I don't think \doublespacing should set a different factor (for all sizes) just because it happens in the scope of `\large`

Maybe simply store `\xdef\setspace@basefontsize{\f@size}` at package loading time and test against that.

Thanks for taking care.

**Comment by davidcarlisle** [comment]
> Why? I think all classes set \f@size, don't they?

yes but some may (and do) set \f@size to 10bp rather than 10pt at \@ptsize=0 , so not testing @ptsize would make a difference in those cases

The package works now (with a warning) for all classes whether or not they set @ptsize. Your suggested change would remove the warning but change the layout, I don't really see any need to change the layout. 1.667 and 1.655 are essentially arbitrary factors of approx 1 2/3 .The \@ptsize  test forces  1.655 if @ptsize  is 2 but that is just an arbitrary adjustment for backwards compatibility, there is no need to do that in cases where it is not already happening. So just simply dropping the warning would seem a simpler and more natural change

**Comment by jspitz** [comment]
OK, thanks. I am looking forward for the fix you are talking about (it's not yet in the repo, unless I have missed something).

**Comment by davidcarlisle** [comment]
I'm not sure any fix is required, I'll let others comment. At most I think we could drop the warning or downgrade it to an info

**Comment by jspitz** [comment]
Well, load setspace with a class that does not set `\@ptsize`, e.g. beamer, and set `\onehalfspacing`. The document fails with an error message that is quite opaque.

**Comment by jspitz** [comment]
And note that there is no warning in the current code. This is only in my proposed change.

**Comment by davidcarlisle** [comment]
@jspitz  ah sorry we can guard the tests with a test for \@ptsize

```
\newcommand{\onehalfspacing}{%
  \setstretch{1.25}%  default
  \ifx\@ptsize\@undefined\else
  \ifcase \@ptsize \relax % 10pt
    \setstretch {1.25}%
  \or % 11pt
    \setstretch {1.213}%
  \or % 12pt
    \setstretch {1.241}%
  \fi
  \fi
}

\newcommand{\doublespacing}{%
  \setstretch {1.667}%  default
  \ifx\@ptsize\@undefined\else
  \ifcase \@ptsize \relax % 10pt
    \setstretch {1.667}%
  \or % 11pt
    \setstretch {1.618}%
  \or % 12pt
    \setstretch {1.655}%
  \fi
  \fi
}
```

**Comment by jspitz** [comment]
Yes, this would be a minimal fix for the problem.

**Comment by davidcarlisle** [comment]
6.7b has been submitted to ctan, thanks for the report.
